### Problem 1: Arrays

In [7]:
import numpy as np

def arrays(arr):
    # The input list is first converted to numpy array
    # Then the type of elements is changed to float value
    # Finally the array is reversed using the flip function of numpy.
    return numpy.flip(np.array(arr).astype(np.float64))

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

3 4 6 8
[8. 6. 4. 3.]


### Problem 2: Shape & Reshape

In [6]:
arr = input().strip().split(' ')
# The input list is converted to numpy array and reshaped into a 2-D array using
# the reshape function by specifying the shape.
print("Reshaped Array:\n",numpy.reshape(numpy.array(arr).astype(numpy.int32),(3,3)))

1 2 3 4 5 6 7 8 9
Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Problem 3: Transpose and Flatten

In [7]:
import numpy 
n, m = map(int,input().split())
# 
rows = [list(map(int,input().split())) for i in range(n)]
print("Input Array: ",rows)
arr = numpy.array(rows)

print("Transpose of array:\n",numpy.transpose(arr))
print("Flattened array:\n",arr.flatten())



2 2
2 3
3 4
Input Array:  [[2, 3], [3, 4]]
Transpose of array:
 [[2 3]
 [3 4]]
Flattened array:
 [2 3 3 4]


### Problem 4: Zeroes and One

In [10]:
import numpy

N = tuple(map(int, input().split()))
print("\nZeros array\n",numpy.zeros(N, int))
print("\n Ones array\n",numpy.ones(N, int))


2 2 2

Zeros array
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

 Ones array
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


### Problem 5: Concatenate

In [11]:
n,m,p = map(int,input().split())

arr1 = [list(map(int,input().split())) for i in range(n)] 
arr2 = [list(map(int,input().split())) for i in range(m)]
print("Array 1: ",arr1)
print("Array 2: ",arr2)
print("Concatenated Array:\n",numpy.concatenate((arr1,arr2),axis=0)) # concatenate arrays on axis = 0 i.e by rows

4 3 2
1 2
1 2
1 2
1 2
3 4
2 4
3 5
Array 1:  [[1, 2], [1, 2], [1, 2], [1, 2]]
Array 2:  [[3, 4], [2, 4], [3, 5]]
Concatenated Array:
 [[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [2 4]
 [3 5]]


###  Problem 6: Eye and Identity

In [12]:
n,m = map(int,input().split())
print("Identity matrix:\n")
if n==m:
    print(numpy.identity(n))
else:
    print(numpy.eye(n,m))

3 3
Identity matrix:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Problem 7: Array Mathematics

In [13]:
n,m = map(int,input().split())
arr1 = numpy.array([list(map(int,input().split())) for i in range(n)])
arr2 = numpy.array([list(map(int,input().split())) for i in range(n)])
print("Array 1: ",arr1)
print("Array 2: ",arr2)
print("Array Addition: ",numpy.add(arr1,arr2))
print("Array subtraction: ",numpy.subtract(arr1,arr2))
print("Array Mul: ",numpy.multiply(arr1,arr2))
print("Array Division: ",arr1//arr2)
print("Array mod: ",numpy.mod(arr1,arr2))
print("Power: ",numpy.power(arr1,arr2))

1 4
1 2 3 4
5 6 7 8
Array 1:  [[1 2 3 4]]
Array 2:  [[5 6 7 8]]
Array Addition:  [[ 6  8 10 12]]
Array subtraction:  [[-4 -4 -4 -4]]
Array Mul:  [[ 5 12 21 32]]
Array Division:  [[0 0 0 0]]
Array mod:  [[1 2 3 4]]
Power:  [[    1    64  2187 65536]]


### Problem 8: floor, ceil, rint

In [14]:
numpy.set_printoptions(legacy='1.13')

arr2 = numpy.array(list(map(float,input().split())))
print("Input Array: ",arr2)
print("Floor of Array: ",numpy.floor(arr2))
print("Ceil of Array: ",numpy.ceil(arr2))
print("Rint of Array: ",numpy.rint(arr2),sep='\n')

1.1 2.3 4.4 6.7 8.8 4.5 9.7
Input Array:  [ 1.1  2.3  4.4  6.7  8.8  4.5  9.7]
Floor of Array:  [ 1.  2.  4.  6.  8.  4.  9.]
Ceil of Array:  [  2.   3.   5.   7.   9.   5.  10.]
Rint of Array: 
[  1.   2.   4.   7.   9.   4.  10.]


### Problem 9: Sum and Prod

In [15]:
n,m = map(int,input().split())

arr1 = numpy.array([list(map(int,input().split())) for i in range(n)])
print("Input Array: ",arr1)
arr_sum = numpy.sum(arr1,axis=0)
print("Sum of elements ny row: ",arr_sum)
print("Product of the sum: ",numpy.prod(arr_sum))

2 2
1 2
3 4
Input Array:  [[1 2]
 [3 4]]
Sum of elements ny row:  [4 6]
Product of the sum:  24


### Problem 10: Min and max

In [16]:
n,m = map(int,input().split())

arr1 = numpy.array([list(map(int,input().split())) for i in range(n)])
print("Input Array: ",arr1)
arr_min = numpy.min(arr1,axis=1)
print("Minimum of Array: ",arr_min)
print("Maximum of Array: ",numpy.max(arr_min))

4 2
2 4
5 6
3 4
7 2
Input Array:  [[2 4]
 [5 6]
 [3 4]
 [7 2]]
Minimum of Array:  [2 5 3 2]
Maximum of Array:  5


### Problem 11: mean,var and std

In [17]:
n,m = map(int,input().split())

arr1 = numpy.array([list(map(int,input().split())) for i in range(n)])
print("Input Array: ",arr1)
print("Mean: ",numpy.mean(arr1,axis=1))
print("Variance: ",numpy.var(arr1,axis=0))
print("Standard Variance: ",round(numpy.std(arr1),11))

2 2
1 2
3 4
Input Array:  [[1 2]
 [3 4]]
Mean:  [ 1.5  3.5]
Variance:  [ 1.  1.]
Standard Variance:  1.11803398875


### Problem 12: Dot and cross

In [18]:
n = int(input())
a = numpy.array([list(map(int,input().split())) for i in range(n)])
b = numpy.array([list(map(int,input().split())) for i in range(n)])
print("A: ",a)
print("B: ",b)
print("Matrix Multiplication: ",numpy.matmul(a,b))

2
2 2
1 4
6 4
3 2
A:  [[2 2]
 [1 4]]
B:  [[6 4]
 [3 2]]
Matrix Multiplication:  [[18 12]
 [18 12]]


### Problem 13: Inner and outer

In [19]:
a = numpy.array(list(map(int,input().split())))
b = numpy.array(list(map(int,input().split())))

print("Inner Product: ",numpy.inner(a,b))
print("Outer Product: ",numpy.outer(a,b))

4 5 6
5 4 3
Inner Product:  58
Outer Product:  [[20 16 12]
 [25 20 15]
 [30 24 18]]


### Problem 14: Polynomials

In [45]:
coef = numpy.array(list(map(float,input().split())))
x = int(input())

print(numpy.polyval(coef, x))

1.1 2 3
0
3.0


### Problem 15: Linear Algebra

In [50]:
n = int(input())
a = numpy.array([list(map(float,input().split())) for i in range(n)])

print(round(numpy.linalg.det(a),2))


2
1.1 1.1
1.1 1.1
0.0
